package exception_Error;

import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class Error2 {

	public static void main(String[] args) {
		// try And catch block.
		
//		 Example-1
//		System.out.println(50/0);
//		System.out.println("rest of the code: ");
		
//		Example-2
//try {
//	System.out.println(50/0);
//}
//catch(ArithmeticException e) {
//	System.out.println(e);
//}
//System.out.println("rest of the code: ");
		
//		Example-3
//		try {
//			System.out.println(50/0);
//			System.out.println("executing after try block: ");
//		}
//		catch(ArithmeticException e) {
//			System.out.println(e);
//		}
//		System.out.println("rest of the code: ");
		
//		Example-4
//		try {
//			int a[]= {1,2,3};
//			System.out.println(a[9]);
//		}
//		catch(Exception e) {
//			System.out.println(e);
//		}
//		System.out.println("rest of the code: ");
//		
//		Example-5
//		try {
//			int a[]= {1,2,3};
//			System.out.println(a[9]);
//		}
//		catch(Exception e) {
//			System.out.println("Array index out of bounds: ");
//		}
//		System.out.println("rest of the code: ");
//		
//		Example-6
//		int a=50;
//		int b=0;
//		try {
//			System.out.println(a/b);
//		}
//		catch(Exception e) {
//			System.out.println(a/(b+2));
//		}
		
//		Example-7
//		try {
//			System.out.println(50/0);
//		}
//		catch(NullPointerException e) {
//			System.out.println(e);
//		}
//		System.out.println("rest of the code: ");
		
//		Example-8
//		 PrintWriter pw;  
//	        try {  
//	            pw = new PrintWriter("jtp.txt"); //may throw exception   
//	            pw.println("saved");  
//	        }
//	        catch(FileNotFoundException e) {
//	        	System.out.println("File not found: ");
//	        }
//	        System.out.println("rest of the code: ");
	}

}
